name: Continous delivery

on:
  push:
    branches:
      - "main"

jobs:
  quay-build-push:
    runs-on: ubuntu-latest
    outputs:
      registry-path: ${{ steps.push-to-quay.outputs.registry-path }}
      registry-paths: ${{ steps.push-to-quay.outputs.registry-paths }}
    steps:
      - uses: actions/checkout@v2
      - name: Create Unity_lic.ulf
        run: echo "$UNITY_2021_ULF" > Unity_lic.ulf
        env:
          UNITY_2021_ULF: ${{ secrets.UNITY_2021_ULF }}
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: asset-bundle-converter
          tags: ${{ github.sha }} ${{ inputs.docker-tag }}
          layers: true #cache
          dockerfiles: |
            ./Dockerfile
          build-args: |
            COMMIT_HASH=${{ github.sha }}
      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/decentraland
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  deployment:
    needs: [quay-build-push]
    name: "Deploy to: dev"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "${{ needs.quay-build-push.outputs.registry-path }}"
          serviceName: asset-bundle-converter
          env: dev
          token: ${{ secrets.GITHUB_TOKEN }}