name: Docker (CI)

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Unity_lic.ulf
        run: echo "$UNITY_2021_ULF" > Unity_lic.ulf
        env:
          UNITY_2021_ULF: ${{ secrets.UNITY_2021_ULF }}
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: asset-bundle-converter
          tags: ${{ github.sha }} ${{ inputs.docker-tag }}
          layers: true #cache
          dockerfiles: |
            ./Dockerfile
          build-args: |
            COMMIT_HASH=${{ github.sha }}

